name: CI

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop, feature/* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Type check
        run: npm run check:types
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
      - name: Check for accidental JS artifacts in src
        run: |
          if find server/src client/services client/test -type f \( -name '*.js' -o -name '*.js.map' -o -name '*.d.ts' \) ! -path '*/dist-server/*' ! -path '*/.next/*' | grep .; then
            echo '❌ JS artifacts found in source! Clean up before merging.'
            exit 1
          fi 