name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: echo "NEXT_PUBLIC_SUPABASE_URL=http://localhost:54321" >> client/.env
      - run: echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=dummy" >> client/.env
      - run: echo "NEXT_PUBLIC_API_URL=http://localhost:5000" >> client/.env
      - run: echo "NEXT_PUBLIC_SENTRY_DSN=dummy" >> client/.env
      - run: echo "NEXT_PUBLIC_SENTRY_ENVIRONMENT=ci" >> client/.env
      - run: echo "NEXT_PUBLIC_SENTRY_RELEASE=ci" >> client/.env
      - run: echo "SENTRY_DSN=dummy" >> client/.env
      - run: echo "SENTRY_ENVIRONMENT=ci" >> client/.env
      - run: echo "SENTRY_RELEASE=ci" >> client/.env
      - run: echo "SENTRY_ORG=scorelytic" >> client/.env
      - run: echo "SENTRY_PROJECT=javascript-nextjs" >> client/.env
      - run: echo "SENTRY_AUTH_TOKEN=dummy" >> client/.env
      - run: npm test

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      # Inject correct env vars for Next.js + Supabase
      - run: echo "NEXT_PUBLIC_SUPABASE_URL=http://localhost:54321" >> client/.env
      - run: echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=dummy" >> client/.env
      - run: echo "NEXT_PUBLIC_API_URL=http://localhost:5000" >> client/.env
      - run: echo "NEXT_PUBLIC_SENTRY_DSN=dummy" >> client/.env
      - run: echo "NEXT_PUBLIC_SENTRY_ENVIRONMENT=ci" >> client/.env
      - run: echo "NEXT_PUBLIC_SENTRY_RELEASE=ci" >> client/.env
      - run: echo "SENTRY_DSN=dummy" >> client/.env
      - run: echo "SENTRY_ENVIRONMENT=ci" >> client/.env
      - run: echo "SENTRY_RELEASE=ci" >> client/.env
      - run: echo "SENTRY_ORG=scorelytic" >> client/.env
      - run: echo "SENTRY_PROJECT=javascript-nextjs" >> client/.env
      - run: echo "SENTRY_AUTH_TOKEN=dummy" >> client/.env
      - run: echo "SUPABASE_URL=http://localhost:54321" >> server/.env
      - run: echo "SUPABASE_SERVICE_ROLE_KEY=dummy" >> server/.env
      - run: echo "LOGTAIL_SOURCE_TOKEN=dummy" >> server/.env
      - run: echo "SENTRY_DSN=dummy" >> server/.env
      - run: echo "SENTRY_ENVIRONMENT=ci" >> server/.env
      - run: echo "SENTRY_RELEASE=ci" >> server/.env
      - run: echo "OPENAI_API_KEY=dummy" >> server/.env
      - run: echo "DISABLE_OPENAI=true" >> server/.env
      - run: echo "LLM_PROMPT_STYLE=DEFAULT" >> server/.env
      - run: echo "PORT=5000" >> server/.env
      - run: echo "YOUTUBE_API_KEY=dummy" >> server/.env
      - run: npm run build --workspace=client
      - run: npm run start --workspace=client -- -p 4000 &
      - run: npx wait-on http://localhost:4000
      - run: npx playwright install --with-deps
      - run: npx playwright test client/test/e2e
