name: CI Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  unit:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL: http://localhost:54321
      NEXT_PUBLIC_SUPABASE_ANON_KEY: dummy
      NEXT_PUBLIC_API_URL: http://localhost:5000
      NEXT_PUBLIC_SENTRY_DSN: dummy
      NEXT_PUBLIC_SENTRY_ENVIRONMENT: ci
      NEXT_PUBLIC_SENTRY_RELEASE: ci
      SENTRY_DSN: dummy
      SENTRY_ENVIRONMENT: ci
      SENTRY_RELEASE: ci
      SENTRY_ORG: dummy
      SENTRY_PROJECT: dummy
      SENTRY_AUTH_TOKEN: dummy
      SUPABASE_URL: http://localhost:54321
      SUPABASE_SERVICE_ROLE_KEY: dummy
      LOGTAIL_SOURCE_TOKEN: dummy
      OPENAI_API_KEY: dummy
      DISABLE_OPENAI: false
      LLM_PROMPT_STYLE: DEFAULT
      PORT: 5000
      YOUTUBE_API_KEY: dummy

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: sudo apt-get update && sudo apt-get install -y ffmpeg jq

      - run: npm ci

      - name: Write env files
        run: echo '${{ toJson(env) }}' | bash ./scripts/write-envs.sh

      - name: Run unit tests
        run: npm test

  e2e:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL: http://localhost:54321
      NEXT_PUBLIC_SUPABASE_ANON_KEY: dummy
      NEXT_PUBLIC_API_URL: http://localhost:5000
      NEXT_PUBLIC_SENTRY_DSN: dummy
      NEXT_PUBLIC_SENTRY_ENVIRONMENT: ci
      NEXT_PUBLIC_SENTRY_RELEASE: ci
      SENTRY_DSN: dummy
      SENTRY_ENVIRONMENT: ci
      SENTRY_RELEASE: ci
      SENTRY_ORG: dummy
      SENTRY_PROJECT: dummy
      SENTRY_AUTH_TOKEN: dummy
      SUPABASE_URL: http://localhost:54321
      SUPABASE_SERVICE_ROLE_KEY: dummy
      LOGTAIL_SOURCE_TOKEN: dummy
      OPENAI_API_KEY: dummy
      DISABLE_OPENAI: false
      LLM_PROMPT_STYLE: DEFAULT
      PORT: 5000
      YOUTUBE_API_KEY: dummy

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: sudo apt-get update && sudo apt-get install -y ffmpeg jq

      - run: npm ci

      - name: Write env files
        run: echo '${{ toJson(env) }}' | bash ./scripts/write-envs.sh

      - run: cp client/.env client/.env.local

      - name: Build client
        run: npm run build --workspace=client

      - name: Start client in background
        run: nohup npm run start --workspace=client -- -p 4000 > client.log 2>&1 &

      - name: Wait for client
        run: npx wait-on http://localhost:4000

      - name: Install Playwright deps
        run: npx playwright install --with-deps

      - name: Run e2e tests
        run: npx playwright test client/test/e2e
