name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      # Inject correct env vars for Next.js + Supabase
      - run: echo "NEXT_PUBLIC_SUPABASE_URL=http://localhost:54321" >> client/.env
      - run: echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=dummy" >> client/.env
      # If server-side tests need Supabase, add:
      # - run: echo "SUPABASE_URL=http://localhost:54321" >> server/.env
      # - run: echo "SUPABASE_SERVICE_ROLE_KEY=dummy" >> server/.env
      - run: npm run build --workspace=client
      - run: npm run start --workspace=client -- -p 4000 &
      - run: npx wait-on http://localhost:4000
      - run: npx playwright install --with-deps
      - run: npx playwright test client/test/e2e
