name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      # Inject dummy Supabase env vars for build/prerender
      - run: echo "SUPABASE_URL=http://localhost:54321" >> client/.env
      - run: echo "SUPABASE_ANON_KEY=dummy" >> client/.env
      # Build and start Next.js app on port 4000
      - run: npm run build --workspace=client
      - run: npm run start --workspace=client -- -p 4000 &
      - run: npx wait-on http://localhost:4000
      # Install Playwright browsers and run E2E
      - run: npx playwright install --with-deps
      - run: npx playwright test client/test/e2e
